/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  test1                                  */
/*      FILE         :  hardware_setup.c                       */
/*      DESCRIPTION  :  Hardware Initialization                */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX63N                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                
                                                                           
                                                                           
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 08/07/2013                                        */
/************************************************************************/

#include "iodefine.h"
#include "r_bsp_config.h"
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif

/***********************************************************************************************************************
Private global variables and functions
***********************************************************************************************************************/
/* MCU I/O port configuration function delcaration */
static void output_ports_configure(void);

/* Interrupt configuration function delcaration */
static void interrupts_configure(void);

/* MCU peripheral module configuration function declaration */
static void peripheral_modules_enable(void);

static void operating_frequency_set(void);



void HardwareSetup(void)
{
	operating_frequency_set();
    output_ports_configure();
    interrupts_configure();
    peripheral_modules_enable();
}



/***********************************************************************************************************************
* Function name: output_ports_configure
* Description  : Configures the port and pin direction settings, and sets the pin outputs to a safe level.
* Arguments    : none
* Return value : none
***********************************************************************************************************************/
static void output_ports_configure(void)
{
    SYSTEM.PRCR.WORD = 0xA50B;			/* Protect off */
    MPC.PWPR.BIT.B0WI = 0 ;     		/* Unlock protection register */
    MPC.PWPR.BIT.PFSWE = 1 ;    		/* Unlock MPC registers */

    MSTP(EDMAC) = 0 ;                   /* Power up ethernet block */

    /* Port 0 - DAC & ethernet IRQ */
    PORT0.PODR.BYTE = 0x00 ;    /* All outputs low to start */
    PORT0.PDR.BYTE  = 0x10 ;    /* DA1 is an ouput, all others are inputs */

    /* Port 1 - I2C and USB over-current & pull-up control */
    PORT1.PODR.BYTE = 0x00 ;    /* All outputs low to start */
    PORT1.PDR.BYTE  = 0x80 ;    /* AUD_R (P1.7) is an output, all others are inputs (I2C lines setup by
    *                              I2C driver later */

    /* Port 2 - USB control and some expansion signals */
    PORT2.PODR.BYTE = 0x02 ;    /* All outputs low to start except backlight enable */
    PORT2.PDR.BYTE  = 0x02 ;    /* All inputs except backlight enable - some will be overridden by USB driver later */

    /* Port 3 - Serial port & JTAG */
    PORT3.PODR.BYTE = 0x00 ;    /* All outputs low to start */
    PORT3.PDR.BIT.B2  = 0x01 ;  /* Transmit line for SCI6/ CAN 0 TxD is an output */

    /* Port 4 -  */
    PORT4.PODR.BYTE = 0x00 ;    /* These are all inputs */
    PORT4.PDR.BYTE  = 0x00 ;    /* Analog inputs and switches, all inputs */
    PORT4.PMR.BYTE  = 0x00 ;

    /* Port 5 -  */
    PORT5.PODR.BYTE = 0x00 ;    /* All outputs low to start */
    PORT5.PDR.BYTE  = 0x13 ;    /* SCI 2 TxD, LCD_RS, PWMLP_OUT are outputs */
    MPC.P50PFS.BYTE = 0x0A ;    /* P50 is TXD2. */
    MPC.P52PFS.BYTE = 0x0A ;    /* P52 is RXD2. */
    PORT5.PMR.BYTE  = 0x05 ;    /* P50 and P52 are used for SCI2. */

    /* Port A - Ethernet MDIO */
    PORTA.PODR.BYTE = 0x00 ;    /* */
    PORTA.PMR.BYTE  = 0x00 ;    /* All GPIO for now */
    MPC.PA3PFS.BYTE = 0x11 ;    /* PA3 is RMII MDIO */
    MPC.PA4PFS.BYTE = 0x11 ;    /* PA4 is RMII MDC */
    MPC.PA5PFS.BYTE = 0x11 ;    /* PA5 is RMII LINK_STA */
    PORTA.PMR.BYTE  = 0x38 ;    /* PA3-5 are used by Ethernet peripheral */
    PORTA.PDR.BYTE  = 0xFF ;    /* */

    /* Port B - Ethernet signals */
    PORTB.PODR.BYTE = 0x00 ;    /* */
    PORTB.PMR.BYTE  = 0x00 ;    /* All GPIO for now */
    MPC.PB0PFS.BYTE = 0x12 ;    /* PB0 is RMII_RXD1 */
    MPC.PB1PFS.BYTE = 0x12 ;    /* PB1 is RMII_RXD0 */
    MPC.PB2PFS.BYTE = 0x12 ;    /* PB2 is REF50CK */
    MPC.PB3PFS.BYTE = 0x12 ;    /* PB3 is RMI_RX_ERR */
    MPC.PB4PFS.BYTE = 0x12 ;    /* PB4 is RMII_TXD_EN */
    MPC.PB5PFS.BYTE = 0x12 ;    /* PB5 is RMII_TXD0 */
    MPC.PB6PFS.BYTE = 0x12 ;    /* PB6 is RMII_TXD1 */
    MPC.PB7PFS.BYTE = 0x12 ;    /* PB7 is RMII_CRS_DV */
    PORTB.PMR.BYTE  = 0xFF ;    /* All pins assigned to peripheral */
    PORTB.PDR.BYTE  = 0xF0 ;    /* */

    /* Port C -  SPI signals, chip selects, peripheral reset */
    PORTC.PODR.BYTE = 0x00 ;    /* */
    PORTC.PMR.BYTE  = 0x00 ;    /* All GPIO for now */
    MPC.PC5PFS.BYTE = 0x0D ;    /* PC5 is RSPCKA */
    MPC.PC6PFS.BYTE = 0x0D ;    /* PC6 is MOSIA */
    MPC.PC7PFS.BYTE = 0x0D ;    /* PC7 is MISOA */
    PORTC.PMR.BYTE  = 0xE0 ;    /* PC5-7 assigned to SPI peripheral */
    PORTC.PODR.BYTE = 0x17 ;    /* All outputs low to start */
    PORTC.PDR.BYTE  = 0x7F ;    /* All outputs except MISO */


    /* Port D -  LED's */
    PORTD.PODR.BYTE = 0xFF ;    /* All outputs LED's off */
    PORTD.PDR.BYTE  = 0xFF ;    /* All outputs */

    /* Port E -  LED's, WiFi & PMOD control */
    PORTE.PODR.BYTE = 0xFF ;    /* All LED's off, all chip selects inactive */
    PORTE.PDR.BYTE  = 0x7F ;    /* All outputs except PMOD_MISO */

    /* Port J -  WiFi chip select */
    PORTJ.PODR.BYTE = 0x04 ;    /* WiFi CS de-asserted at power up */
    PORTJ.PDR.BYTE  = 0x04 ;    /* WiFi CS is an output */
}

/***********************************************************************************************************************
* Function name: interrupts_configure
* Description  : Configures interrupts used
* Arguments    : none
* Return value : none
***********************************************************************************************************************/
static void interrupts_configure(void)
{
    /* Add code here to setup additional interrupts */
}

/***********************************************************************************************************************
* Function name: peripheral_modules_enable
* Description  : Enables and configures peripheral devices on the MCU
* Arguments    : none
* Return value : none
***********************************************************************************************************************/
static void peripheral_modules_enable(void)
{
    /* Add code here to enable peripherals used by the application */
}

/***********************************************************************************************************************
* Function name: operating_frequency_set
* Description  : Configures the clock settings for each of the device clocks
* Arguments    : none
* Return value : none
***********************************************************************************************************************/
static void operating_frequency_set(void)
{
    /* Used for constructing value to write to SCKCR register. */
    uint32_t temp_clock = 0;

    /*
    Clock Description              Frequency
    ----------------------------------------
    Input Clock Frequency............  12 MHz
    PLL frequency (x16).............. 192 MHz
    Internal Clock Frequency.........  96 MHz
    Peripheral Clock Frequency.......  48 MHz
    USB Clock Frequency..............  48 MHz
    External Bus Clock Frequency.....  24 MHz */

	volatile unsigned int i;

    /* Protect off. */
    SYSTEM.PRCR.WORD = 0xA50B;

    /* Uncomment if not using sub-clock */
	//SYSTEM.SOSCCR.BYTE = 0x01;          /* stop sub-clock */
    SYSTEM.SOSCCR.BYTE = 0x00;			/* Enable sub-clock for RTC */

    /* Wait 131,072 cycles * 12 MHz = 10.9 ms */
    SYSTEM.MOSCWTCR.BYTE = 0x0D;

    /* PLL wait is 4,194,304 cycles (default) * 192 MHz (12 MHz * 16) = 20.1 ms*/
    SYSTEM.PLLWTCR.BYTE = 0x0F;

    /* Set PLL Input Divisor. */
    SYSTEM.PLLCR.BIT.PLIDIV = PLL_DIV >> 1;

    /* Set PLL Multiplier. */
    SYSTEM.PLLCR.BIT.STC = PLL_MUL - 1;

    /* EXTAL ON */
    SYSTEM.MOSCCR.BYTE = 0x00;

    /* PLL ON */
    SYSTEM.PLLCR2.BYTE = 0x00;

	for(i = 0;i< 0x168;i++)
    {
        /* Wait over 12ms */
     //   nop() ;
		__asm volatile( "nop");
		//todo:nop
	}

    /* Figure out setting for FCK bits. */
#if   FCK_DIV == 1
    /* Do nothing since FCK bits should be 0. */
#elif FCK_DIV == 2
    temp_clock |= 0x10000000;
#elif FCK_DIV == 4
    temp_clock |= 0x20000000;
#elif FCK_DIV == 8
    temp_clock |= 0x30000000;
#elif FCK_DIV == 16
    temp_clock |= 0x40000000;
#elif FCK_DIV == 32
    temp_clock |= 0x50000000;
#elif FCK_DIV == 64
    temp_clock |= 0x60000000;
#else
    #error "Error! Invalid setting for FCK_DIV in r_bsp_config.h"
#endif

    /* Figure out setting for ICK bits. */
#if   ICK_DIV == 1
    /* Do nothing since ICK bits should be 0. */
#elif ICK_DIV == 2
    temp_clock |= 0x01000000;
#elif ICK_DIV == 4
    temp_clock |= 0x02000000;
#elif ICK_DIV == 8
    temp_clock |= 0x03000000;
#elif ICK_DIV == 16
    temp_clock |= 0x04000000;
#elif ICK_DIV == 32
    temp_clock |= 0x05000000;
#elif ICK_DIV == 64
    temp_clock |= 0x06000000;
#else
    #error "Error! Invalid setting for ICK_DIV in r_bsp_config.h"
#endif

    /* SDCLK Pin Output and BCLK Pin Output are disabled by default. */
    temp_clock |= 0x00C00000;

    /* Figure out setting for BCK bits. */
#if   BCK_DIV == 1
    /* Do nothing since BCK bits should be 0. */
#elif BCK_DIV == 2
    temp_clock |= 0x00010000;
#elif BCK_DIV == 4
    temp_clock |= 0x00020000;
#elif BCK_DIV == 8
    temp_clock |= 0x00030000;
#elif BCK_DIV == 16
    temp_clock |= 0x00040000;
#elif BCK_DIV == 32
    temp_clock |= 0x00050000;
#elif BCK_DIV == 64
    temp_clock |= 0x00060000;
#else
    #error "Error! Invalid setting for BCK_DIV in r_bsp_config.h"
#endif

    /* Figure out setting for PCKA bits. */
#if   PCKA_DIV == 1
    /* Do nothing since PCKA bits should be 0. */
#elif PCKA_DIV == 2
    temp_clock |= 0x00001000;
#elif PCKA_DIV == 4
    temp_clock |= 0x00002000;
#elif PCKA_DIV == 8
    temp_clock |= 0x00003000;
#elif PCKA_DIV == 16
    temp_clock |= 0x00004000;
#elif PCKA_DIV == 32
    temp_clock |= 0x00005000;
#elif PCKA_DIV == 64
    temp_clock |= 0x00006000;
#else
    #error "Error! Invalid setting for PCKA_DIV in r_bsp_config.h"
#endif

    /* Figure out setting for PCKB bits. */
#if   PCKB_DIV == 1
    /* Do nothing since PCKB bits should be 0. */
#elif PCKB_DIV == 2
    temp_clock |= 0x00000100;
#elif PCKB_DIV == 4
    temp_clock |= 0x00000200;
#elif PCKB_DIV == 8
    temp_clock |= 0x00000300;
#elif PCKB_DIV == 16
    temp_clock |= 0x00000400;
#elif PCKB_DIV == 32
    temp_clock |= 0x00000500;
#elif PCKB_DIV == 64
    temp_clock |= 0x00000600;
#else
    #error "Error! Invalid setting for PCKB_DIV in r_bsp_config.h"
#endif

    /* Bottom byte of SCKCR register must be set to 0x11 */
    temp_clock |= 0x00000011;

    /* Set SCKCR register. */
    SYSTEM.SCKCR.LONG = temp_clock;

    /* Re-init temp_clock to use to set SCKCR2. */
    temp_clock = 0;

    /* Figure out setting for IEBCK bits. */
#if   IEBCK_DIV == 2
    temp_clock |= 0x00000001;
#elif IEBCK_DIV == 4
    temp_clock |= 0x00000002;
#elif IEBCK_DIV == 6
    temp_clock |= 0x0000000C;
#elif IEBCK_DIV == 8
    temp_clock |= 0x00000003;
#elif IEBCK_DIV == 16
    temp_clock |= 0x00000004;
#elif IEBCK_DIV == 32
    temp_clock |= 0x00000005;
#elif IEBCK_DIV == 64
    temp_clock |= 0x00000006;
#else
    #error "Error! Invalid setting for IEBCK_DIV in r_bsp_config.h"
#endif

    /* Figure out setting for UCK bits. */
#if   UCK_DIV == 3
    temp_clock |= 0x00000020;
#elif UCK_DIV == 4
    temp_clock |= 0x00000030;
#else
    #error "Error! Invalid setting for UCK_DIV in r_bsp_config.h"
#endif

    /* Set SCKCR2 register. */
    SYSTEM.SCKCR2.WORD = (uint16_t)temp_clock;

    /* Choose clock source. Default for r_bsp_config.h is PLL. */
    SYSTEM.SCKCR3.WORD = ((uint16_t)CLOCK_SOURCE) << 8;

    /* Protect on. */
    SYSTEM.PRCR.WORD = 0xA500;
}


